function result0304191645 = importBillerudPulp(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULT0304191645 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  RESULT0304191645 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  result0304191645 = importfile("C:\Users\augustbr\Desktop\cTemp_24092019\2019\Rohdaten\result_030419_1645\result_030419_1645.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Sep-2019 08:17:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Lp", "Lc", "Width", "Wall", "Var5"];
opts.SelectedVariableNames = ["Lp", "Lc", "Width", "Wall"];
opts.VariableTypes = ["double", "double", "double", "double", "string"];
opts = setvaropts(opts, 5, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 5, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
result0304191645 = readtable(filename, opts);

%% Convert to output type
result0304191645 = table2array(result0304191645);
end