function nodalCoTest = importNodes(filename, startRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   NODALCOTEST = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   NODALCOTEST = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   nodalCoTest = importfile('nodalCoTest', 6, 157557);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/07/01 13:54:37
fileID0 = fopen(filename,'r');
 linecount = 0;
 tline = fgetl(fileID0);
 while ischar(tline)
   tline = fgetl(fileID0);
   linecount = linecount+1;
 end
fclose(fileID0);
%% Initialize variables.
if nargin<2
    startRow = 6;
   endRow = linecount-1;
elseif nargin < 3
    endRow = linecount-1;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%8f%16f%16f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');
% linecount = 0;
% tline = fgetl(fileID);
% while ischar(tline)
%   tline = fgetl(fileID);
%   linecount = linecount+1;
% end
% endRow = linecount-1;
%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
nodalCoTest = [dataArray{1:end-1}];
